#!/usr/bin/env bash

set -euo pipefail

PARADEDB_PORT="${PARADEDB_PORT:-5432}"
PARADEDB_USER="${PARADEDB_USER:-postgres}"
PARADEDB_PASSWORD="${PARADEDB_PASSWORD:-postgres}"
PARADEDB_DB="${PARADEDB_DB:-postgres}"

export PARADEDB_PORT PARADEDB_USER PARADEDB_PASSWORD PARADEDB_DB
export PARADEDB_TEST_DSN="postgres://${PARADEDB_USER}@localhost:${PARADEDB_PORT}/${PARADEDB_DB}"
export PGPASSWORD="${PARADEDB_PASSWORD}"
export DATABASE_URL="${DATABASE_URL:-postgres://${PARADEDB_USER}:${PARADEDB_PASSWORD}@localhost:${PARADEDB_PORT}/${PARADEDB_DB}}"
