# Generated by Django 5.2.12 on 2026-03-10 14:03

from __future__ import annotations

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = []

    operations: ClassVar = [
        migrations.CreateModel(
            name="JsonItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "db_table": "json_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JsonItemNoExpand",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "db_table": "json_items_no_expand",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MockItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("in_stock", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "db_table": "mock_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("in_stock", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
    ]
