"""ParadeDB integration for Django ORM."""

__version__ = "0.3.0"

from paradedb.functions import (
    Agg,
    Score,
    Snippet,
    SnippetPositions,
    Snippets,
    paradedb_index_segments,
    paradedb_indexes,
    paradedb_verify_all_indexes,
    paradedb_verify_index,
)
from paradedb.indexes import BM25Index, IndexExpression
from paradedb.queryset import ParadeDBManager, ParadeDBQuerySet
from paradedb.search import (
    All,
    Empty,
    Exists,
    FuzzyTerm,
    Match,
    MoreLikeThis,
    ParadeDB,
    ParadeOperator,
    Parse,
    ParseWithField,
    Phrase,
    PhrasePrefix,
    Proximity,
    ProximityArray,
    ProximityRegex,
    ProxRegex,
    Range,
    RangeRelation,
    RangeTerm,
    RangeType,
    Regex,
    RegexPhrase,
    Term,
    TermSet,
)

__all__ = [
    "Agg",
    "All",
    "BM25Index",
    "Empty",
    "Exists",
    "FuzzyTerm",
    "IndexExpression",
    "Match",
    "MoreLikeThis",
    "ParadeDB",
    "ParadeDBManager",
    "ParadeDBQuerySet",
    "ParadeOperator",
    "Parse",
    "ParseWithField",
    "Phrase",
    "PhrasePrefix",
    "ProxRegex",
    "Proximity",
    "ProximityArray",
    "ProximityRegex",
    "Range",
    "RangeRelation",
    "RangeTerm",
    "RangeType",
    "Regex",
    "RegexPhrase",
    "Score",
    "Snippet",
    "SnippetPositions",
    "Snippets",
    "Term",
    "TermSet",
    "paradedb_index_segments",
    "paradedb_indexes",
    "paradedb_verify_all_indexes",
    "paradedb_verify_index",
]
